### ISSUE TITLE
SwiftLint autocorrect or SwiftFormat or both?

### ISSUE THREAD

**Issue by AvdLee** [WeTransfer/WeTransfer-iOS-CI#77]
In our PRs, we had several discussions regarding using SwiftLint autocorrect or SwiftFormat. Let's discuss here what's best for us to implement. Should we use both? Or just one of them?

@kevinrenskers @amirdew your experience will be very useful here!

**Comment by kevinrenskers** [comment]
Personally I use both, as they do different things. SwiftLint is great for catching things like force unwrapping or non-weak delegates, whereas SwiftFormat "just" does reformatting.

**Comment by kevinrenskers** [comment]
And I use SwiftFormat also as a builds phase script, so it reformats when you build (rather than manually run or when you commit or something). The downside is that your undo stack can be wiped out when you build, but in practice I find it a small price to pay.

**Comment by AvdLee** [comment]
Alright, that sounds good. What would your suggestion be @kevinrenskers? Use both SwiftLint autocorrect and SwiftFormat or just SwiftFormat? And how are buildtimes affected by using SwiftFormat locally?

**Comment by kevinrenskers** [comment]
I personally use SwiftLint without autocorrect, plus SwiftFormat. SwiftFormat adds almost nothing to build times, it's not noticeable (less than a second for sure).

The reason why I don't use autocorrect is because I want to be forced to change it myself, so I get in the habit of writing "best practices" code haha.

In Xcode make sure you run swiftformat before swiftlint. And make sure swiftlint doesn't do any formatting related changes.

As an example, here is my personal swiftlint config:

```
opt_in_rules:
  - implicitly_unwrapped_optional
  - prohibited_super_call
  - redundant_nil_coalescing
  - anyobject_protocol
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - identical_operands
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - operator_usage_whitespace
  - overridden_super_call
disabled_rules:
  - file_length
  - line_length
  - function_body_length
  - function_parameter_count
  - type_body_length
  - trailing_comma
  - cyclomatic_complexity
  - switch_case_alignment
type_name:
  min_length: 2
  max_length: 60
identifier_name:
  min_length: 2
  excluded: [i, x, y]
nesting:
  type_level: 2
excluded:
  - DiffryTests
 ```

and my swiftformat config:

```
--indent 2
--indentcase true
--patternlet inline
--disable unusedArguments
```
